// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:5069ea8e-f9d1-4881-a304-d5c98f986ca6",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_k7x2yrgfB",
    "aws_user_pools_web_client_id": "58pglca3glc5egckgh9frd333k",
    "aws_appsync_graphqlEndpoint": "https://46kep5rcfrghxaoseuu2lelycu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
